name: Cloud Build
on:
  push:
    branches: [ dev ]
  workflow_dispatch:

# THIS is the correct way to force Qt 6 across the entire build
env:
  DESKTOP_APP_QT6: 1

jobs:
  build_windows:
    runs-on: windows-2022
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Cache Third-Party Libraries
        uses: actions/cache@v4
        with:
          path: |
            Libraries
            ThirdParty
          # Updated to "v2" so it ignores the broken architecture folder we just made
          key: ${{ runner.os }}-tdesktop-qt6-v2-libs-${{ hashFiles('Telegram/build/prepare/**') }}

      - name: Run Telegram Prepare
        run: |
          # Back to normal. The environment variable above tells it to use Qt 6.
          .\Telegram\build\prepare\win.bat

      - name: Configure and Build
        env:
          MY_API_ID: ${{ secrets.TDESKTOP_API_ID }}
          MY_API_HASH: ${{ secrets.TDESKTOP_API_HASH }}
        run: |
          .\Telegram\configure.bat x64 -D TDESKTOP_API_ID=$env:MY_API_ID -D TDESKTOP_API_HASH=$env:MY_API_HASH
          cmake --build out --config Release --target Telegram

      - name: Upload Finished App
        uses: actions/upload-artifact@v7
        with:
          name: OjjotMod-Binary
          path: out/Release/Telegram.exe